# Generated by Django 4.2.6 on 2023-10-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productentry',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
